CREATE DATABASE RETAIL_ANALYTICS;

CREATE WAREHOUSE RETAIL_WH
WITH WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE;


USE DATABASE RETAIL_ANALYTICS;

USE WAREHOUSE RETAIL_WH;


CREATE SCHEMA LANDING;
CREATE SCHEMA STAGING;
CREATE SCHEMA MART;



CREATE OR REPLACE STORAGE INTEGRATION
retail_s3_int
TYPE= EXTERNAL_STAGE
STORAGE_PROVIDER=S3
STORAGE_AWS_ROLE_ARN='arn:aws:iam::609789243227:role/SnowflakeRetailS3Role'
ENABLED=TRUE
STORAGE_ALLOWED_LOCATIONS=('s3://aastha-retail-project/');

DESC STORAGE INTEGRATION
retail_s3_int;


CREATE OR REPLACE FILE FORMAT
LANDING.csv_ff
TYPE= CSV
FIELD_DELIMITER=','
SKIP_HEADER=1
FIELD_OPTIONALLY_ENCLOSED_BY='"';

CREATE OR REPLACE STAGE
LANDING.retail_stage
URL='s3://aastha-retail-project/'
STORAGE_INTEGRATION=retail_s3_int
FILE_FORMAT=LANDING.csv_ff;


LIST @LANDING.retail_stage;






DESC TABLE
SLEEKMART_OMS.L1_LANDING.CUSTOMERS;


CREATE OR REPLACE TABLE
LANDING.CUSTOMERS_RAW
(
CUSTOMERID VARCHAR(10),
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR(50),
EMAIL VARCHAR(100),
PHONE VARCHAR(50),
ADDRESS VARCHAR(100),
CITY VARCHAR(50),
STATE VARCHAR(2),
ZIPCODE VARCHAR(10),
UPDATED_AT TIMESTAMP_NTZ(9)

);


COPY INTO LANDING.CUSTOMERS_RAW
FROM @LANDING.RETAIL_STAGE/customers/
FILE_FORMAT=(FORMAT_NAME=LANDING.CSV_FF);
RETAIL_ANALYTICS.DBT_RANIRAY.DIM_CUSTOMERSRETAIL_ANALYTICS.DBT_RANIRAY.DIM_CUSTOMERS

select count(*)
from LANDING.CUSTOMERS_RAW;

SELECT * FROM LANDING.CUSTOMERS_RAW
LIMIT 10;





DESC TABLE
SLEEKMART_OMS.L1_LANDING.ORDERS;


CREATE OR REPLACE TABLE
LANDING.ORDERS_RAW
(
ORDERID NUMBER(38,0),
ORDERDATE DATE,
CUSTOMERID VARCHAR(10),
EMPLOYEEID NUMBER(38,0),
STOREID VARCHAR(10),
STATUS VARCHAR(2),
UPDATED_AT TIMESTAMP_NTZ(9)
);

COPY INTO LANDING.ORDERS_RAW
FROM @LANDING.RETAIL_STAGE/orders/
FILE_FORMAT=(FORMAT_NAME=LANDING.CSV_FF);

SELECT COUNT(*) FROM
LANDING.ORDERS_RAW;

SELECT * FROM LANDING.ORDERS_RAW
LIMIT 10;




DESC TABLE
SLEEKMART_OMS.L1_LANDING.ORDERITEMS;

CREATE OR REPLACE TABLE
LANDING.ORDER_ITEMS_RAW
(
ORDERID NUMBER(38,0),
ORDERITEMID NUMBER(38,0),
PRODUCTID NUMBER(38,0),
QUANTITY NUMBER(38,0),
UNITPRICE NUMBER(10,2),
UPDATED_AT TIMESTAMP_NTZ(9)
);

COPY INTO LANDING.ORDER_ITEMS_RAW
FROM @LANDING.RETAIL_STAGE/order_items/
FILE_FORMAT=(FORMAT_NAME=LANDING.CSV_FF);

SELECT COUNT(*) FROM 
LANDING.ORDER_ITEMS_RAW;









DESC TABLE
SLEEKMART_OMS.L1_LANDING.PRODUCTS;

CREATE OR REPLACE TABLE
LANDING.PRODUCTS_RAW
(
PRODUCTID NUMBER(38,0),
NAME VARCHAR(100),
CATEGORY VARCHAR(50),
RETAILPRICE NUMBER(38,0),
SUPPLIERPRICE NUMBER(38,0),
SUPPLIERID NUMBER(38,0),
UPDATED_AT TIMESTAMP_NTZ(9)
);

COPY INTO LANDING.PRODUCTS_RAW
FROM @LANDING.RETAIL_STAGE/products/
FILE_FORMAT=(FORMAT_NAME=LANDING.CSV_FF);

SELECT COUNT(*) FROM
LANDING.PRODUCTS_RAW;





--Analysis karo
--Total Sales
select sum(sales_amount) as total_sales
from fact_sales;


--Top 10 customers by sales
select customerid,sum(sales_amount) as total_sales
from fact_sales
group by customerid
order by total_sales desc
limit 10;


--Top 10 products by revenue
select productid,sum(sales_amount) as total_sales
from fact_sales
group by productid
order by total_sales desc
limit 10;

--Total sales by date
select orderdate,
sum(sales_amount) as total_sales
from fact_sales
group by orderdate
order by orderdate;


--Total quantity sold
select sum(total_quantity) as
total_quantity_sold
from fact_sales;




